<?php
// $Id: user_picture_block.module,v 1.11 2011/02/23 10:48:05 boran Exp $


/**

/**
 * Implementation of hook_init().
 */
function user_block_init() {
  //$_moduleName_='user_block';
  //drupal_add_css(drupal_get_path('module', $_moduleName_) . '/' . $_moduleName_  . '.css');
  drupal_add_css(drupal_get_path('module', 'user_block') . '/user_block.css');
}


/**
 * Implements hook_block_info().
 */
function user_block_block_info() {
  $_moduleName_='user_block';
  $blocks = array();
  $blocks['user-block']['info'] =  t(ucfirst($_moduleName_));
  $blocks['user-block']['cache'] = DRUPAL_NO_CACHE;   // maybe CACHE_PER_USER ?
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function user_block_block_view($delta) {
  global  $user, $base_path, $base_url, $language;
  $uid=-1;
  $block = array();
  if ( arg(0) == 'node' and is_numeric(arg(1)) and arg(2) == FALSE ) {
  	$node=node_load(arg(1));
  	if($node->type=="article"){
  		$uid=$user->uid;
  	}else{
  		$uid=($node->uid);
  		$block['subject']=t('Submitted by');
  	}
  }else{
  	$uid=$user->uid;
  }
  if ($uid < 1) { 
  	 return false;
  }
  $puser=user_load($uid);
  $_moduleName_='user_block';
/* scan user's reputration from qtr module: agent_file*/
  $user_rep = drupal_get_path('module', 'qtr') . "/agent_file"; 
  $variables['rep']=0;
  $rep=0;
  if($ifs = file($user_rep)){
  foreach ($ifs as $line) {
    $words = explode("\t", $line);
    $i = (int) $words[0];
    $rep++;
    if($i==$uid){
      $variables['rep']=$rep;
      break;
    }
  }
  }
  
 // $img_prefix=$base_url . "/" . variable_get('file_public_path', conf_path() . '/files');

  // create block content for normal viewing
  $block['content'] = "<div class=$_moduleName_>";

  

  $variables['account'] = $puser;
  $variables['user_picture'] = '';
  template_preprocess_user_picture($variables);
  //$block['content'] .= "<div class=picture>";
  $block['content'] .= $variables['user_picture'];
  //$block['content'] .= "</div>";

  // Show Username? Trim long usernames
   $userlen=variable_get('user_picture_userlen', 20);
   $userdisp=$puser->name;
   if (strlen($puser->name) > $userlen) {
     $userdisp=substr($puser->name, 0, $userlen) . '..';
   }
   if (variable_get('user_block_showuser','1')=='1') {
     $block['content'] .='<div class="user-info"><h3>' .l($userdisp, "user/$puser->uid" ) . "</h3>";
   }
   user_build_content($puser);
 $content=$puser->content;
  if (isset($content['first_name']) || isset($content['last_name'])){
      $block['content'] .= "<div class=userlevel>" . $content['first_name'][0]['#markup'] .' '. $content['last_name'][0]['#markup']. "</div>";
  }
  if (isset($content['research_fields'])) {
      $block['content'] .= "<div class=userlevel>" . $content['research_fields'][0]['#markup'] . "</div>";
  }
  if (isset($content['position'])||isset($content['institution'])) {
  	$block['content'] .= "<div class=userlevel>";  
      if(isset($content['position'])){
      	$block['content'] .= $content['position'][0]['#markup'];
      }
      if(isset($content['position'])&& isset($content['institution'])){
      	$block['content'] .= ', ';
      }
      if(isset($content['institution'])){
      $block['content'] .= $content['institution'][0]['#markup'];
      }
      $block['content'] .= "</div>";
  }
  if (isset($content['country'])) {
      $block['content'] .= "<div class=userlevel>" . $content['country'][0]['#markup'] . "</div>";
  }
  if (isset($content['website'])) {
      $block['content'] .= '<div class=userlevel>' . $content['website'][0]['#markup'] . "</div>";
  }


  $block['content'] .= "</div>"; // class=$_moduleName_
  $block['content'].="<div class=\"user-score\"><p>Rank</p>".$variables['rep']."</div></div>";
  return $block;
}

/* user reputation*/
function user_block_cron(){
  $result_upload = db_query("SELECT uid, nid, created FROM {node} where status=1")->fetchAll();
  $result_vote = db_query("SELECT uid, entity_id, timestamp FROM {votingapi_vote} where entity_type='node' and value=1")->fetchAll();
  $path_agents = drupal_get_path('module', 'qtr') . "/EF_complete_new.dat";
  $file=fopen($path_agents,'w');
  foreach ($result_upload as $node) {
    fwrite($file, "$node->uid\t$node->nid\tU\t$node->created\n");
  }
  foreach ($result_vote as $vote) {
    fwrite($file, "$vote->uid\t$vote->entity_id\tV\t$vote->timestamp\n");
  }
  fclose($file);
  drupal_http_request('http://'.$_SERVER['HTTP_HOST'].url('qtr/demo'));
  
}
