<?php
// $Id: user_picture_block.module,v 1.11 2011/02/23 10:48:05 boran Exp $


/**

/**
 * Implementation of hook_init().
 */
function user_block_init() {
  //$_moduleName_='user_block';
  //drupal_add_css(drupal_get_path('module', $_moduleName_) . '/' . $_moduleName_  . '.css');
  drupal_add_css(drupal_get_path('module', 'user_block') . '/user_block.css');
}


/**
 * Implements hook_block_info().
 */
function user_block_block_info() {
  $_moduleName_='user_block';
  $blocks = array();
  $blocks['user-block']['info'] =  t(ucfirst($_moduleName_));
  $blocks['user-block']['cache'] = DRUPAL_NO_CACHE;   // maybe CACHE_PER_USER ?
  return $blocks;
}

/*
 * Implements hook_block_configure
 */
function user_block_block_configure($delta = '') {
  if ($delta == 'user-block') {
  	 $radio['rank_type_num'] = array(
      '#type' => 'radio',
      '#title' => t('Show user\'s rank with the formate of rank number'),
      '#description' =>  NULL,
      '#return_value' => 'num',
      '#default_value' => variable_get('rank_type','percent'),
	  '#parents' => array('rank_type'),
    );
     $radio['rank_type_percent'] = array(
      '#type' => 'radio',
      '#title' => t('Show user\'s rank with the formate of percentage'),
      '#description' =>  NULL,
      '#return_value' => 'percent',
      '#default_value' => variable_get('rank_type','percent'),
      '#parents' => array('rank_type'),
    );
  	$form['rank_type'] = array(
    '#type' => 'item',
    '#title' => t('Select a rank type to display in this block'),
  	);
  	$form['rank_type'] += $radio;
  	
   
    return $form;
  }
}
  
/*
 * Implements hook_block_save
 */
function user_block_block_save($delta, $edit = array()) {
  if ($delta == 'user-block') {
   variable_set('rank_type',$edit['rank_type']);
  }
}



/**
 * Implements hook_block_view().
 */
function user_block_block_view($delta) {
  global  $user, $base_path, $base_url, $language;
  $uid=-1;
  $block = array();
  if ( arg(0) == 'node' and is_numeric(arg(1)) and arg(2) == FALSE ) {
  	$node=node_load(arg(1));
  	if($node->type=="article"){
  		$uid=$user->uid;
  	}else{
  		$uid=($node->uid);
  		$block['subject']=t('Submitted by');
  	}
  }else{
  	$uid=$user->uid;
  }
  if ($uid < 1) { 
  	 return false;
  }
  $puser=user_load($uid);
  $_moduleName_='user_block';
  
 // $img_prefix=$base_url . "/" . variable_get('file_public_path', conf_path() . '/files');

  // create block content for normal viewing
  $block['content'] = '<div class='.$_moduleName_.'> ';

  

  $variables['account'] = $puser;
  $variables['user_picture'] = '';
  template_preprocess_user_picture($variables);
  //$block['content'] .= "<div class=picture>";
  $block['content'] .= '<div class="user_pic">'.$variables['user_picture'];
  
    $block['content'].="<div class=\"user-score\"><h4>Top ";
 
  
  if(variable_get('rank_type','percent')=='num'){
  	  $variables['rank']= qtr_get_value('qtr_reputation','rank',$uid);
  	$block['content'].=$variables['rank']?$variables['rank'][0]:'&#8734;';
  }else{
  	 $variables['rep']= qtr_get_value('qtr_reputation','percentile',$uid);
  	$block['content'].= $variables['rep']?ceil(100*$variables['rep'][0]).'%':"100%";
  }
   $block['content'].='</h4></div></div>';
  //$block['content'] .= "</div>";

  // Show Username? Trim long usernames
   $userlen=variable_get('user_picture_userlen', 20);
   $userdisp=$puser->name;
   if (strlen($puser->name) > $userlen) {
     $userdisp=substr($puser->name, 0, $userlen) . '..';
   }
   if (variable_get('user_block_showuser','1')=='1') {
     $block['content'] .='<div class="user-info"><h3>' .l($userdisp, "user/$puser->uid" ) . "</h3>";
   }
   
    $langcode = $GLOBALS['language_content']->language;
   $puser->content = array();
   // Build fields content.
  field_attach_prepare_view('user', array($puser->uid => $puser), 'full', $langcode);
  entity_prepare_view('user', array($puser->uid => $puser), $langcode);
  $puser->content += field_attach_view('user', $puser, 'full', $langcode);
   module_invoke('profile', 'user_view',$puser, 'full', $langcode); //profile_user_view($puser);  
 $content=$puser->content;
  if (isset($content['first_name']) || isset($content['last_name'])){
      $block['content'] .= "<div class=userlevel>" . $content['first_name'][0]['#markup'] .' '. $content['last_name'][0]['#markup']. "</div>";
  }
//  if (isset($content['research_fields'])) {
//     $block['content'] .= "<div class=userlevel>" . $content['research_fields'][0]['#markup'] . "</div>";
//  }
  if (isset($content['position'])||isset($content['institution'])) {
  	$block['content'] .= "<div class=userlevel>";  
      if(isset($content['position'])){
      	$block['content'] .= $content['position'][0]['#markup'];
      }
      if(isset($content['position'])&& isset($content['institution'])){
      	$block['content'] .= ', ';
      }
      if(isset($content['institution'])){
      $block['content'] .= $content['institution'][0]['#markup'];
      }
      $block['content'] .= "</div>";
  }
  if (isset($content['country'])) {
      $block['content'] .= "<div class=userlevel>" . $content['country'][0]['#markup'] . "</div>";
  }
  if (isset($content['website'])) {
      $block['content'] .= '<div class=userlevel>' . $content['website'][0]['#markup'] . "</div>";
  }


  $block['content'] .= "</div>"; // class=$_moduleName_
  $block['content'].=' <div class="user-history"><h2><a href="'.url('user/'.$puser->uid).'">History of contributions</a></h2></div>';

  $block['content'].="</div>";
  return $block;
}

/**
 * Implements hook_user_view().
 */
 
 function user_block_user_view($account){
 	$chart=render(qtr_chart_reputation($account->uid));
 	 $account->content['Reputation History'] = array(
        '#type' => 'user_profile_item', 
        '#title' => "Reputation Over Time", 
        '#markup'=>$chart,
        '#weight' => 100, 
        '#attributes' => array('class' => array('profile-qtr-history')),
      );
 }
 /*
  * Implements MODULE_preprocess_HOOK().
  */
 function user_block_preprocess_user_profile(&$variables) {
  $account = $variables['elements']['#account'];
  $querypost = db_select('node', 'n')
  			->fields('n',array('nid'))->condition('n.uid', $account->uid)->condition('n.promote', 1)->condition('n.status', 1)
    ->condition('n.type', array('paper','paper_from_arxiv','news','event','editorial','bookreview'),'in')->execute()->rowCount();
  $queryblog = db_select('node', 'n')
  			->fields('n',array('nid'))->condition('n.uid', $account->uid)->condition('n.promote', 1)
    ->condition('n.status', 1)
    ->condition('n.type', 'blog')->execute()->rowCount();
    $querycomment = db_select('comment', 'c')
  			->fields('c',array('cid'))->condition('c.uid', $account->uid)
    ->condition('c.status', 1)->execute()->rowCount();
 	$variables['historyNo']['post']=$querypost;
 	$variables['historyNo']['comment']=$querycomment;
 	$variables['historyNo']['blog']=$queryblog;
}
